name = "shorter"
type = "javascript"

# You must set the CF_ACCOUNT_ID and CF_ZONE_ID
# environment variables before deploying
workers_dev = false
# Note: you must manually add a worker link to the management domain
# if you are using two different origins. Otherwise you can just add
# replace the below line with:
#routes = ["https://wffl.<domain>/*", "https://management.<domain>/*"]
route = "https://wffl.link/*"

compatibility_date = "2021-11-09"

[vars]
SHORT_DOMAIN = "wffl.link"
MANAGEMENT_DOMAIN = "links.wafflehacks.tech"

[[kv_namespaces]]
binding = "LINKS"
id = "2d62bc3067404ade9c9a71d9bc6d7c96"

[build]
command = "worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
